nodeLinker: node-modules

plugins:
  - checksum: 8ef42c07114b0262b35d16e5c0147ae55b1d4747a8650f8b1fb2495302b7d49c539af19f3b9bcf8c9c6b2d2abb62db7a4c6537b161e2b125694f0a06de78c39f
    path: .yarn/plugins/@yarnpkg/plugin-script-daemon.cjs
    spec: "https://raw.githubusercontent.com/zwade/yarn-plugin-script-daemon/refs/heads/master/bundles/%40yarnpkg/plugin-script-daemon.js"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
